import pandas as pd
import csv
import os

class ModelCSV():
    """Model object which contains all methods for the CSV Editor"""
    def open_csv_file(self, path):
        """reads dataframe from path"""
        df = pd.read_csv(path)
        return df

    def save_csv(self, filename: str): # TODO write treeview
        """create csv writer to save file"""
        file = open(filename, 'w', newline='')
        csv_writer = csv.writer(file)
        return csv_writer
    
    def delete_csv(self, path):
        os.remove(path)

    def row_content(self, dataframe):
        """extracts the contents of the row in the dataframe. excludes heading"""
        df = dataframe.to_numpy().tolist()
        return df

    def col_content(self, dataframe) -> list:
        """returns list of columns in the dataframe"""
        col_lst = list(dataframe.columns)
        return col_lst

    def str_query(self, pairs: dict, dataframe):
        """string query to match the entry with the dataframe

        Args:
            pairs (dict): pairs of {column: value} in the entry box
            dataframe (_type_): dataframe to conduct a query
    
        Returns:
            DataFrame: dataframe containing match result from query
        """
        for col, value in pairs.items():
            # query expression that checks if the column contains the inputted value
            query_string = f"`{col}`.str.contains('{value}', na=False)"
            # dataframe generated by query function to evaluate the columns with matched expression
            df = dataframe.query(query_string, engine="python")
        return df
    
    def _parse_drop_files(self, filename: str) -> list:
        """When dropping a file to listbox, removes curly braces on file name 
        when the file has space by taking the string inside the curly braces

        Args:
            filename (str): name of the file can be with or without space

        Returns:
            list: list of filepath names
        """
        size = len(filename)
        res = [] # list of file paths
        name = "" 
        idx = 0
        while idx<size:
            # create var j when encountering an opening curly bracket
            if filename[idx] == "{":
                # start iteration after the curly bracket to take the contents
                j = idx + 1
                # iterate over string until it reaches closing brace
                while filename[j] != "}":
                    # append string to the name var
                    name += filename[j]
                    # increase index position
                    j+=1
                # append name to list of results
                res.append(name)
                # resets variables to iterate again
                name=""
                idx=j
            # for filepath without curly braces, append filepath name when it reaches space which implies the end of the filepath name
            elif filename[idx]== " " and name != "":
                res.append(name)
                name=""
            # continue to append the idx value as long as the value is not equal to space which implies the end of the filepath name
            elif filename[idx] != " ":
                name += filename[idx]
            idx+=1
        # checks the filepath string if there are remaining filepaths
        if name != "":
            # appends the remaining file path name
            res.append(name)

        return res
    
    def entry_to_pairs(self, entry: str) -> dict:
        """Converts entry sting to a dictionary of {column: value} pairs

        Args:
            entry (str): string in the entry box

        Returns:
            dict: contains {column: value} pairs of the entry string
        """
        # converts the strings separated by comma to list ['country=Philippines', 'year=2020']
        entry_split = entry.split(",")
        # a dictionary of the entry searches by pair
        pairs = {}
        # transforms items in list into pairs in the dictionary 
        for pair in entry_split:
            # splits the value on the equal sign
            pair_split = pair.split("=")
            # confirms if the list contains two values which will be key and value
            if len(pair_split) == 2:
                col = pair_split[0] # key
                lookup_value = pair_split[1] # val
                # pairs the key and the value together and inserts it to the dictionary
                pairs[col] = lookup_value 
        return pairs
